In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
df_train=pd.read_csv("/content/drive/MyDrive/train.csv",encoding="utf-16le")
df_train

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,class
0,-262.16965,96.769220,40.706000,24.221952,-67.632935,9.503783,-23.372135,12.542497,-20.795818,2.684272,...,1.752180,-2.671875,1.473892,-0.775247,-1.263207,-0.691721,0.942970,-2.105847,0.594554,10
1,-390.61800,188.915990,-22.474472,-50.801810,-0.716926,4.473694,-20.689625,-16.345764,-22.348412,11.738687,...,1.426527,-0.469320,-1.651692,1.668184,1.700142,-2.844166,2.626280,-0.156019,1.161202,8
2,-228.32678,70.577700,19.398410,60.041080,-66.451540,15.624901,-42.324210,-12.154552,-39.571940,9.660892,...,1.321854,0.886343,2.230334,1.725458,1.413675,2.050256,-1.346849,1.265808,-0.958732,10
3,-373.93695,45.851852,35.936066,66.907130,-48.138170,-15.640406,-42.387028,-21.534351,8.726290,-6.009919,...,5.098388,0.868991,4.276999,3.263133,0.398069,-1.683457,0.815522,-0.287744,0.980611,3
4,-244.53513,125.362610,12.599331,26.531328,-16.807745,10.794590,-0.248945,1.321505,-35.607800,-4.275824,...,3.567559,-0.542143,-1.499802,-0.493320,1.118007,-1.182481,2.510826,-1.751707,-0.449377,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1036796,-418.41394,126.188290,-35.935837,7.780997,25.802970,-8.645332,-1.643332,-23.078842,-53.265870,-11.933481,...,-1.458249,0.806896,-1.528040,4.451213,1.559036,1.217997,3.251558,-2.137240,0.417038,1
1036797,-105.44799,6.320216,-7.477610,20.126873,-60.493637,-11.150801,-48.281470,21.191418,-48.365253,17.547180,...,0.261530,3.216615,0.532624,-3.918297,1.911419,1.270757,-1.843479,1.181025,0.766983,5
1036798,-217.83534,79.282850,-18.183273,2.055270,-42.001970,-21.168346,18.647870,9.738131,-28.376400,-7.662221,...,4.691188,0.625502,-2.883734,0.357516,1.646154,-1.668007,-1.394715,0.694054,1.461395,5
1036799,-292.07477,138.789800,-61.054016,22.720840,-38.708030,-1.865384,-31.775976,33.406300,-28.931612,-4.569540,...,0.838813,-1.921822,1.643628,-5.701487,3.002022,2.424216,-2.324061,0.066277,-0.707022,8
1036800,-270.14530,48.913330,-57.417060,23.962498,-26.321575,-22.015144,0.344490,29.481707,-13.302599,13.708033,...,-0.526953,2.485775,-1.273223,1.893252,-2.009185,0.172084,-1.306244,-1.633317,0.587621,6

In [ ]:
df_train_pr2=df_train.iloc[:,0:39]
df_train_pr2

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,-262.16965,96.769220,40.706000,24.221952,-67.632935,9.503783,-23.372135,12.542497,-20.795818,2.684272,...,1.684740,1.752180,-2.671875,1.473892,-0.775247,-1.263207,-0.691721,0.942970,-2.105847,0.594554
1,-390.61800,188.915990,-22.474472,-50.801810,-0.716926,4.473694,-20.689625,-16.345764,-22.348412,11.738687,...,5.459565,1.426527,-0.469320,-1.651692,1.668184,1.700142,-2.844166,2.626280,-0.156019,1.161202
2,-228.32678,70.577700,19.398410,60.041080,-66.451540,15.624901,-42.324210,-12.154552,-39.571940,9.660892,...,-0.912153,1.321854,0.886343,2.230334,1.725458,1.413675,2.050256,-1.346849,1.265808,-0.958732
3,-373.93695,45.851852,35.936066,66.907130,-48.138170,-15.640406,-42.387028,-21.534351,8.726290,-6.009919,...,0.794287,5.098388,0.868991,4.276999,3.263133,0.398069,-1.683457,0.815522,-0.287744,0.980611
4,-244.53513,125.362610,12.599331,26.531328,-16.807745,10.794590,-0.248945,1.321505,-35.607800,-4.275824,...,1.802472,3.567559,-0.542143,-1.499802,-0.493320,1.118007,-1.182481,2.510826,-1.751707,-0.449377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1036796,-418.41394,126.188290,-35.935837,7.780997,25.802970,-8.645332,-1.643332,-23.078842,-53.265870,-11.933481,...,2.691588,-1.458249,0.806896,-1.528040,4.451213,1.559036,1.217997,3.251558,-2.137240,0.417038
1036797,-105.44799,6.320216,-7.477610,20.126873,-60.493637,-11.150801,-48.281470,21.191418,-48.365253,17.547180,...,-0.049626,0.261530,3.216615,0.532624,-3.918297,1.911419,1.270757,-1.843479,1.181025,0.766983
1036798,-217.83534,79.282850,-18.183273,2.055270,-42.001970,-21.168346,18.647870,9.738131,-28.376400,-7.662221,...,-0.800492,4.691188,0.625502,-2.883734,0.357516,1.646154,-1.668007,-1.394715,0.694054,1.461395
1036799,-292.07477,138.789800,-61.054016,22.720840,-38.708030,-1.865384,-31.775976,33.406300,-28.931612,-4.569540,...,-1.015005,0.838813,-1.921822,1.643628,-5.701487,3.002022,2.424216,-2.324061,0.066277,-0.707022
1036800,-270.14530,48.913330,-57.417060,23.962498,-26.321575,-22.015144,0.344490,29.481707,-13.302599,13.708033,...,1.736964,-0.526953,2.485775,-1.273223,1.893252,-2.009185,0.172084,-1.306244,-1.633317,0.587621

In [ ]:
df_YT_test=pd.read_csv("/content/drive/MyDrive/yt_test.csv",encoding="utf-16le")
df_YT_test

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,class
0,-411.78586,107.084030,-35.016550,9.556347,-51.590393,-17.454807,-6.684592,19.923195,-0.913204,-13.269658,...,-0.601352,-2.258642,-0.961004,-2.536742,-0.518441,0.425996,-0.275051,1.802785,0.135182,11
1,-412.20000,66.952640,-43.796112,-6.032129,-28.930810,-8.055288,-44.623580,22.330612,0.880713,-17.887827,...,1.806975,0.899651,0.620508,-3.449689,-0.872460,1.213471,2.340416,-0.683341,0.560399,9
2,-375.19570,67.137300,-46.567635,-23.814450,-31.180065,-15.873762,-1.179296,-0.802936,-38.329308,-16.155727,...,-0.964461,-1.849419,-1.502699,-0.278001,-0.316165,1.462817,1.582685,-0.046116,-0.226688,5
3,-257.15912,136.686860,-15.151343,42.589830,-12.941112,13.701433,3.135206,26.827135,-23.803726,-6.137124,...,-3.611109,-3.352918,-5.533225,-1.291754,0.566484,0.466502,0.118249,-0.152336,-2.035033,4
4,-372.41437,174.226000,-20.677715,-49.338585,1.161477,-8.268505,-34.151497,-16.626900,-20.273457,9.939256,...,-0.156014,0.339570,1.191740,1.921889,-1.747576,-2.148750,-3.670170,-2.478145,0.988430,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458383,-396.60583,77.446320,-75.852690,28.079315,-32.925877,-26.443893,-52.295612,0.096652,-12.999819,-1.526145,...,-0.358343,1.407026,-2.952686,-1.475184,0.586069,1.887304,-0.181552,0.467935,1.208257,2
458384,-299.22842,123.310020,7.559870,42.649666,-39.605522,-6.049403,-2.509343,-27.344952,-2.739587,0.377825,...,4.177836,-0.494439,-1.496540,2.415881,0.236696,-1.665795,0.857356,-1.445670,0.517674,9
458385,-365.92870,108.371810,-34.198765,-11.411422,-68.250440,-16.988136,27.473837,40.424360,-11.268415,27.572632,...,2.762948,2.052040,-3.714298,-2.858613,0.469339,0.655036,0.329624,0.430639,-0.722646,6
458386,-242.74156,56.648650,-7.729671,7.886817,-52.639210,-9.120480,-12.808628,-6.764990,-30.429787,27.231770,...,2.261064,-1.025188,-1.425523,1.990076,1.515512,-3.020056,-1.864373,-3.402804,0.020689,11
458387,-307.74512,109.884445,-35.500057,-2.501202,-25.495182,-17.886910,-46.828770,-41.909393,-9.045969,7.474967,...,0.053658,-0.616463,-2.732750,1.897873,-1.063859,-2.686723,-1.172170,-1.950173,2.419004,9

In [ ]:
YT_gt=[]
for i in df_YT_test['class']:
  YT_gt.append(i-1)
print(np.array(YT_gt))

[10  8  4 ...  5 10  8]

In [ ]:
df_YT_test_pr2=df_YT_test.iloc[:,0:39]
df_YT_test_pr2

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,-411.78586,107.084030,-35.016550,9.556347,-51.590393,-17.454807,-6.684592,19.923195,-0.913204,-13.269658,...,0.399517,-0.601352,-2.258642,-0.961004,-2.536742,-0.518441,0.425996,-0.275051,1.802785,0.135182
1,-412.20000,66.952640,-43.796112,-6.032129,-28.930810,-8.055288,-44.623580,22.330612,0.880713,-17.887827,...,1.035332,1.806975,0.899651,0.620508,-3.449689,-0.872460,1.213471,2.340416,-0.683341,0.560399
2,-375.19570,67.137300,-46.567635,-23.814450,-31.180065,-15.873762,-1.179296,-0.802936,-38.329308,-16.155727,...,-0.287796,-0.964461,-1.849419,-1.502699,-0.278001,-0.316165,1.462817,1.582685,-0.046116,-0.226688
3,-257.15912,136.686860,-15.151343,42.589830,-12.941112,13.701433,3.135206,26.827135,-23.803726,-6.137124,...,-0.442297,-3.611109,-3.352918,-5.533225,-1.291754,0.566484,0.466502,0.118249,-0.152336,-2.035033
4,-372.41437,174.226000,-20.677715,-49.338585,1.161477,-8.268505,-34.151497,-16.626900,-20.273457,9.939256,...,7.529676,-0.156014,0.339570,1.191740,1.921889,-1.747576,-2.148750,-3.670170,-2.478145,0.988430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458383,-396.60583,77.446320,-75.852690,28.079315,-32.925877,-26.443893,-52.295612,0.096652,-12.999819,-1.526145,...,0.986493,-0.358343,1.407026,-2.952686,-1.475184,0.586069,1.887304,-0.181552,0.467935,1.208257
458384,-299.22842,123.310020,7.559870,42.649666,-39.605522,-6.049403,-2.509343,-27.344952,-2.739587,0.377825,...,-3.043006,4.177836,-0.494439,-1.496540,2.415881,0.236696,-1.665795,0.857356,-1.445670,0.517674
458385,-365.92870,108.371810,-34.198765,-11.411422,-68.250440,-16.988136,27.473837,40.424360,-11.268415,27.572632,...,2.579375,2.762948,2.052040,-3.714298,-2.858613,0.469339,0.655036,0.329624,0.430639,-0.722646
458386,-242.74156,56.648650,-7.729671,7.886817,-52.639210,-9.120480,-12.808628,-6.764990,-30.429787,27.231770,...,-0.344558,2.261064,-1.025188,-1.425523,1.990076,1.515512,-3.020056,-1.864373,-3.402804,0.020689
458387,-307.74512,109.884445,-35.500057,-2.501202,-25.495182,-17.886910,-46.828770,-41.909393,-9.045969,7.474967,...,0.744153,0.053658,-0.616463,-2.732750,1.897873,-1.063859,-2.686723,-1.172170,-1.950173,2.419004

In [ ]:
df_PB_test=pd.read_csv("/content/drive/MyDrive/pb_test.csv",encoding="utf-16le")
df_PB_test

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,class
0,-240.76959,68.890490,24.738758,52.012848,-24.524730,-15.960156,-41.487297,-24.408148,-38.216590,1.824532,...,2.073278,-0.328549,-1.240714,1.614787,-1.824536,0.526497,-1.379501,-1.021923,-1.504661,7
1,-265.05383,21.117565,-18.692968,58.172546,-52.124786,-3.415708,-26.523241,-6.554297,-30.746380,16.940443,...,2.192058,0.169128,-0.666537,2.876950,-0.486007,-1.887972,1.116148,-0.716842,-1.571743,7
2,-228.08911,82.332050,36.945385,6.533235,-6.110103,15.911736,-29.157720,13.935959,-37.474630,-5.654282,...,-0.801435,-1.884057,-2.487292,-3.471770,0.046872,3.249748,2.508432,3.066605,1.392084,4
3,-223.09924,71.136350,-111.477770,37.357483,-45.957085,26.291813,-22.182823,14.137628,-28.761913,4.459919,...,0.985187,-6.278759,0.892465,0.608653,1.356059,1.340105,-1.992791,2.965903,-0.285214,8
4,-252.89163,89.295334,-13.920296,67.416470,-77.335860,-1.528272,-16.347061,7.528569,-38.441560,10.473447,...,1.108672,0.960458,-0.427066,-1.508220,2.150583,-3.064189,0.384752,-0.576723,1.847085,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519090,-445.40912,84.335120,16.444494,0.021560,-11.419567,8.158793,-36.891440,17.067474,-46.186540,14.390613,...,-0.158549,1.159429,1.090154,-0.107400,2.346553,-1.535331,0.917100,-0.400383,0.994230,7
519091,-251.05121,179.763120,-6.531735,3.787859,-32.221810,-8.471538,-30.351044,-9.229563,-30.989592,-23.391224,...,2.533073,-1.196888,1.064013,0.649302,2.237176,0.387589,1.268215,0.571119,-0.209862,1
519092,-263.67040,73.252304,-8.735814,-39.943604,-81.523880,-4.361204,-58.637093,-15.350422,-33.017140,-12.329653,...,2.450217,-1.578159,0.984757,1.381474,-2.423508,0.960502,0.535910,-0.303692,1.108810,2
519093,-324.77760,60.515550,-5.155588,17.316307,-29.887794,-54.659092,-3.022050,-38.720820,-14.502830,32.767580,...,1.389364,3.994909,0.387008,4.101245,0.323395,-1.420162,1.302693,-4.045276,-3.609939,11
519094,-455.06370,122.181244,76.108460,62.829050,-4.114570,0.761761,-8.661136,4.803029,-30.808817,-13.982006,...,-0.395756,0.648487,-0.657339,0.759348,-0.468277,0.952282,0.994040,-1.016292,0.000052,3

In [ ]:
df_PB_test_pr2=df_YT_test.iloc[:,0:39]
df_PB_test_pr2

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,-411.78586,107.084030,-35.016550,9.556347,-51.590393,-17.454807,-6.684592,19.923195,-0.913204,-13.269658,...,0.399517,-0.601352,-2.258642,-0.961004,-2.536742,-0.518441,0.425996,-0.275051,1.802785,0.135182
1,-412.20000,66.952640,-43.796112,-6.032129,-28.930810,-8.055288,-44.623580,22.330612,0.880713,-17.887827,...,1.035332,1.806975,0.899651,0.620508,-3.449689,-0.872460,1.213471,2.340416,-0.683341,0.560399
2,-375.19570,67.137300,-46.567635,-23.814450,-31.180065,-15.873762,-1.179296,-0.802936,-38.329308,-16.155727,...,-0.287796,-0.964461,-1.849419,-1.502699,-0.278001,-0.316165,1.462817,1.582685,-0.046116,-0.226688
3,-257.15912,136.686860,-15.151343,42.589830,-12.941112,13.701433,3.135206,26.827135,-23.803726,-6.137124,...,-0.442297,-3.611109,-3.352918,-5.533225,-1.291754,0.566484,0.466502,0.118249,-0.152336,-2.035033
4,-372.41437,174.226000,-20.677715,-49.338585,1.161477,-8.268505,-34.151497,-16.626900,-20.273457,9.939256,...,7.529676,-0.156014,0.339570,1.191740,1.921889,-1.747576,-2.148750,-3.670170,-2.478145,0.988430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458383,-396.60583,77.446320,-75.852690,28.079315,-32.925877,-26.443893,-52.295612,0.096652,-12.999819,-1.526145,...,0.986493,-0.358343,1.407026,-2.952686,-1.475184,0.586069,1.887304,-0.181552,0.467935,1.208257
458384,-299.22842,123.310020,7.559870,42.649666,-39.605522,-6.049403,-2.509343,-27.344952,-2.739587,0.377825,...,-3.043006,4.177836,-0.494439,-1.496540,2.415881,0.236696,-1.665795,0.857356,-1.445670,0.517674
458385,-365.92870,108.371810,-34.198765,-11.411422,-68.250440,-16.988136,27.473837,40.424360,-11.268415,27.572632,...,2.579375,2.762948,2.052040,-3.714298,-2.858613,0.469339,0.655036,0.329624,0.430639,-0.722646
458386,-242.74156,56.648650,-7.729671,7.886817,-52.639210,-9.120480,-12.808628,-6.764990,-30.429787,27.231770,...,-0.344558,2.261064,-1.025188,-1.425523,1.990076,1.515512,-3.020056,-1.864373,-3.402804,0.020689
458387,-307.74512,109.884445,-35.500057,-2.501202,-25.495182,-17.886910,-46.828770,-41.909393,-9.045969,7.474967,...,0.744153,0.053658,-0.616463,-2.732750,1.897873,-1.063859,-2.686723,-1.172170,-1.950173,2.419004

In [ ]:
PB_gt=[]
for i in df_PB_test['class']:
  PB_gt.append(i-1)
print(np.array(PB_gt))

[ 6  6  3 ...  1 10  2]

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.mixture import GaussianMixture
import numpy as np

# **GMM model for full covariance matrix**

In [ ]:
# Full covariance matrix
gmm = GaussianMixture(12, 
                     covariance_type='full', 
                     random_state=0).fit(df_train_pr2)

**Prediction on Youtube data**

In [ ]:
gmm.predict(df_YT_test_pr2)

array([0, 8, 8, ..., 0, 0, 8])

In [ ]:
print('WEIGHTS:', gmm.weights_)

WEIGHTS: [0.11700887 0.07102392 0.07645182 0.07186773 0.10049026 0.09774514
 0.09639382 0.09374081 0.09907402 0.03848201 0.04866972 0.08905186]

**Prediction on Prasar bharti data**

In [ ]:
gmm.predict(df_PB_test_pr2)

array([0, 8, 8, ..., 0, 0, 8])

**Function for accuracy**

In [ ]:
def compute_accuracy(y_true, y_pred):
    correct_predictions = 0
    # iterate over each label and check
    for true, predicted in zip(y_true, y_pred):
        if true == predicted:
            correct_predictions += 1
    # compute the accuracy
    accuracy = correct_predictions/len(y_true)
    return accuracy

**Accuracy for YouTube data**

In [ ]:
YT_true =YT_gt
YT_pred = gmm.predict(df_YT_test_pr2)
# get the accuracy
compute_accuracy(YT_true, YT_pred)

0.09512465422305993

**Accuracy for Prasharbharti data**

In [ ]:
PB_true =PB_gt
PB_pred = gmm.predict(df_PB_test_pr2)
# get the accuracy
compute_accuracy(PB_true, PB_pred)

0.07241449060383938

**BIC values**

In [ ]:
print(gmm.bic(df_PB_test_pr2))
print(gmm.bic(df_YT_test_pr2))

107447673.43179268
107447673.43179268

**AIC values**

In [ ]:
print(gmm.aic(df_PB_test_pr2))
print(gmm.aic(df_YT_test_pr2))

107339095.4300062
107339095.4300062

# **GMM with diag covariance matrix**

In [ ]:
# diag covariance matrix
gmmd= GaussianMixture(12, 
                     covariance_type='diag', 
                     random_state=0).fit(df_train_pr2)

**PB**

In [ ]:
gmmd.predict(df_PB_test_pr2)

array([9, 3, 8, ..., 9, 8, 3])

**YouTube**

In [ ]:
gmmd.predict(df_YT_test_pr2)

array([9, 3, 8, ..., 9, 8, 3])

**Accuracy for youtube**

In [ ]:
YT_true =YT_gt
YT_pred = gmmd.predict(df_YT_test_pr2)
# get the accuracy
compute_accuracy(YT_true, YT_pred)

0.07331125596656107

**Accuracy for Prasharbharti**

In [ ]:
PB_true =PB_gt 
PB_pred = gmmd.predict(df_PB_test_pr2)
# get the accuracy
compute_accuracy(PB_true, PB_pred)

0.07448154962001174

**BIC**

In [ ]:
print(gmmd.bic(df_PB_test_pr2))
print(gmmd.bic(df_YT_test_pr2))

111837142.73628062
111837142.73628062

**AIC**

In [ ]:
print(gmm.aic(df_PB_test_pr2))
print(gmm.aic(df_YT_test_pr2))

107339095.4300062
107339095.4300062

# Performance variation with the number of mixtures in GMM

**Train Test data with 3 mixtures**

In [ ]:
df_train_3_pr2=df_train[df_train["class"].isin([1,2, 3])]
df_YT_test_3_pr2=df_YT_test[df_YT_test["class"].isin([1,2, 3])]
df_PB_test_3_pr2=df_PB_test[df_PB_test["class"].isin([1,2, 3])]

df_train_3=df_train_3_pr2.iloc[:,0:39]
df_YT_test_3=df_YT_test_3_pr2.iloc[:,0:39]
df_PB_test_3=df_PB_test_3_pr2.iloc[:,0:39]

In [ ]:
# diag covariance matrix
gmmd_3= GaussianMixture(3, 
                     covariance_type='diag', 
                     random_state=0).fit(df_train_3)

In [ ]:
print(gmmd_3.predict(df_PB_test_3))
print("############")
print(gmmd_3.predict(df_YT_test_3))

[0 2 1 ... 0 2 1]
############
[2 0 1 ... 2 2 2]

In [ ]:
YT_gt_3=[]
for i in df_YT_test_3_pr2['class']:
  YT_gt_3.append(i-1)
print(np.array(YT_gt_3))

[0 0 2 ... 2 0 1]

In [ ]:
PB_gt_3=[]
for i in df_PB_test_3_pr2['class']:
  PB_gt_3.append(i-1)
print(np.array(PB_gt_3))

[2 2 2 ... 0 1 2]

**Accuracy**

In [ ]:
# Accuracy of 3 mixture of class 1,2,3 data of Youtube  
YT_true_3 =YT_gt_3
YT_pred_3 = gmmd.predict(df_YT_test_3)
# get the accuracy
print(compute_accuracy(YT_true_3, YT_pred_3))


# Accuracy of 3 mixture of class 1,2,3 data of Prasharbharti
PB_true_3 =PB_gt_3
PB_pred_3 = gmmd.predict(df_PB_test_3)
# get the accuracy
print(compute_accuracy(PB_true_3, PB_pred_3))

0.05122126628133074
0.08550533377323216

**Train,Test data with 2 mixtures**

In [ ]:
df_train_2=df_train[df_train["class"].isin([1,2])]
df_YT_test_2=df_YT_test[df_YT_test["class"].isin([1,2])]
df_PB_test_2=df_PB_test[df_PB_test["class"].isin([1,2])]

In [ ]:
# diag covariance matrix
gmmd_2= GaussianMixture(2, 
                     covariance_type='diag', 
                     random_state=0).fit(df_train_2)

In [ ]:
print(gmmd_2.predict(df_PB_test_2))
print("############")
print(gmmd_2.predict(df_YT_test_2))

[0 1 1 ... 0 1 0]
############
[0 1 0 ... 0 0 0]

**Accuracy for two mixtures**

In [ ]:
# Accuracy of 2 mixture of class 1,2 data of Youtube  
YT_true_2 =np.array(df_YT_test_2["class"]) 
YT_pred_2 = gmmd.predict(df_YT_test_2)
# get the accuracy
print(compute_accuracy(YT_true_2, YT_pred_2))


# Accuracy of 3 mixture of class 1,2,3 data of Prasharbharti
PB_true_2 =np.array(df_PB_test_2["class"]) 
PB_pred_2 = gmmd.predict(df_PB_test_2)
# get the accuracy
print(compute_accuracy(PB_true_2, PB_pred_2))

0.10151006711409397
0.09796057183736176